### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by pajlada** [pajlada/patty#8]
If your name is mentioned, it should highlight the message somehow. also highlight the channel.

make this system extensible somehow so there's a list of regular expressions it can use.

Channels should have a different color if they're highlighted, they should also have a number next to their name.

**Comment by Confuseh** [comment]
im gonna try on this today \ pajaHappy /

**Comment by pajlada** [comment]
In MainWindow there can be an std::deque or a similar QT container with regular expressions. 
In the message parser, simply loop through the deque and at the first regular expression that matches, the loop should break (and you highlight the line of course)

**Comment by pajlada** [comment]
In the future we will move a lot of things away from the MainWindow class, but for now we can just throw things into there
